# Packages that are not available in the package manager are listed here and installed with the appropriate method.
#
# Attributes:
#   name: The name of the package.
#   repository: The GitHub repository of the package in the format "owner/repo".
#   systems: The operating systems on which the package should be installed. Must match .chezmoi.os.
#   version_regex (optional): A custom regex to extract the version from `binary --version`.
#   required_architecture (optional): The architecture required for the binary. If the current architecture does not match, the binary will not be installed. Must match .chezmoi.arch.

[binaries]
    [binaries.rip2]
        name                  = "rip"
        repository            = "MilesCranmer/rip2"
        required_architecture = ""
        systems               = ["darwin", "linux"]
        version_regex         = ""
    [binaries.lazygit]
        name                  = "lazygit"
        repository            = "jesseduffield/lazygit"
        required_architecture = ""
        systems               = ["linux"]
        version_regex         = "version=(.*?),"
    [binaries.git-delta]
        name                  = "delta"
        repository            = "dandavison/delta"
        required_architecture = ""
        systems               = ["linux"]
        version_regex         = ""
    [binaries.zoxide]
        name                  = "zoxide"
        repository            = "ajeetdsouza/zoxide"
        required_architecture = ""
        systems               = ["linux"]
        version_regex         = ""
    [binaries.otree]
        name                  = "otree"
        repository            = "fioncat/otree"
        required_architecture = "amd64"
        systems               = ["linux"]
        version_regex         = ""
